webtalk_init -webtalk_dir S:/Cristi/OneDrive - Universitatea Politehnica Bucuresti/ACS -- Seria CC/Anul 3/Semestrul 1/CN2/Lab/Lucrare3/IF_ID/IF_ID.sim/sim_1/behav/xsim/xsim.dir/RISC_V_TB_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Jan  2 21:44:46 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "82b97051-1185-4d58-82a1-feae58b3e6f1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "bb560ed3935d47718a06097adf9806b4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "113" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2304 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "12.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "24" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "all" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "114 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "10 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "127" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "28" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "2.15_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "68936_KB" -context "xsim\\usage"
webtalk_transmit -clientid 486466913 -regid "" -xml S:/Cristi/OneDrive - Universitatea Politehnica Bucuresti/ACS -- Seria CC/Anul 3/Semestrul 1/CN2/Lab/Lucrare3/IF_ID/IF_ID.sim/sim_1/behav/xsim/xsim.dir/RISC_V_TB_behav/webtalk/usage_statistics_ext_xsim.xml -html S:/Cristi/OneDrive - Universitatea Politehnica Bucuresti/ACS -- Seria CC/Anul 3/Semestrul 1/CN2/Lab/Lucrare3/IF_ID/IF_ID.sim/sim_1/behav/xsim/xsim.dir/RISC_V_TB_behav/webtalk/usage_statistics_ext_xsim.html -wdm S:/Cristi/OneDrive - Universitatea Politehnica Bucuresti/ACS -- Seria CC/Anul 3/Semestrul 1/CN2/Lab/Lucrare3/IF_ID/IF_ID.sim/sim_1/behav/xsim/xsim.dir/RISC_V_TB_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
